<a href="https://colab.research.google.com/github/kpranee/google-collabs-for-projects/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is used for fast execution

# Numpy part-1

In [1]:
import numpy as np
demo=[10,20,30]
print(demo)
np.array(demo)

[10, 20, 30]


array([10, 20, 30])

In [2]:
demo2=[10,20,"30"]
np.array(demo2)

array(['10', '20', '30'], dtype='<U21')

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [5]:
x1=np.ones(5)
print(x1)

[1. 1. 1. 1. 1.]


In [6]:
x1[2]="xyz"

ValueError: ignored

In [7]:
y=np.zeros(10)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
y.dtype

dtype('float64')

# Numpy part-2

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
x5=np.ones(5)
x5[3]="2"
print(x5)

[1. 1. 1. 2. 1.]


In [14]:
new_array=np.zeros((3,4,5))
print(new_array)
new_array[0][1][2]
new_array[0][1]

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


array([0., 0., 0., 0., 0.])

In [15]:
new_array.shape

(3, 4, 5)

In [16]:
a=np.zeros(5)
print(a)
a[2:5]

[0. 0. 0. 0. 0.]


array([0., 0., 0.])

In [18]:
twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array)
print(twoD_array[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


In [19]:
twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array[:,1])

[2 5 8]


In [20]:
twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
new_twoD_array[1:3,0]

NameError: ignored

In [21]:
twoD_array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
twoD_array[1:3,0]

array([4, 7])

# Numpy part-3

In [22]:
import numpy as np
import math as m
x=[1,2,3]
y=[3,5,6]
x=x+10

TypeError: ignored

In [23]:
x=np.array([1,2,3])
y=np.array([4,5,6])
x=x+10
print(x)

[11 12 13]


In [26]:
print(x*2)
print(x*y)
print(x**3)

[22 24 26]
[44 60 78]
[1331 1728 2197]


In [28]:
print(x.mean())
print(x.sum())

12.0
36


In [29]:
pts=np.array([4,5,6,7])
value1=((pts-pts.mean())**2).sum()
print(value1)
print(np.sqrt(value1))

5.0
2.23606797749979


In [30]:
m1=np.array([1,2,3])
m2=np.array([4,5,6])
print(m1.dot(m2))

32
